# Generated by Django 4.0.3 on 2024-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('CustomerEmail', models.EmailField(max_length=254, unique=True)),
                ('CustomerPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
