# Generated by Django 4.0.3 on 2024-03-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pancard', models.CharField(max_length=20)),
                ('aadharcard', models.CharField(max_length=24)),
                ('news', models.CharField(max_length=100)),
                ('donate_type', models.CharField(choices=[('Before Dead', 'Before Dead'), ('After Dead', 'After Dead')], max_length=12)),
                ('beforedeath', models.CharField(blank=True, max_length=100, null=True)),
                ('afterdeath', models.CharField(blank=True, max_length=100, null=True)),
                ('question1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question6', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question7', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question8', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question9', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('question10', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
