# Generated by Django 4.0.3 on 2024-03-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.donationform'),
        ),
    ]
